# Generated by Django 4.1 on 2024-09-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Can_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Can_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Error_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Error_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_portfolio', models.TextField()),
                ('Error_reason', models.TextField()),
                ('Error_case_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.error_dim')),
            ],
        ),
        migrations.CreateModel(
            name='Lot_Can_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Can_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.can_dim')),
            ],
        ),
        migrations.CreateModel(
            name='Lot_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lot_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Model_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Specerror_dim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spec_error', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spec_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spec_correct', models.CharField(max_length=50)),
                ('update_at', models.CharField(max_length=50)),
                ('Spec_error_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.specerror_dim')),
            ],
        ),
        migrations.CreateModel(
            name='Model_lc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Error_info_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.error_info')),
                ('Lot_Can_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.lot_can_info')),
                ('Model_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.model_dim')),
            ],
        ),
        migrations.AddField(
            model_name='lot_can_info',
            name='Lot_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.lot_dim'),
        ),
        migrations.AddField(
            model_name='error_info',
            name='Spec_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.spec_info'),
        ),
        migrations.CreateModel(
            name='Cate_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.category_dim')),
                ('Model_lc_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_process.model_lc')),
            ],
        ),
    ]
