# Generated by Django 5.1.1 on 2024-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='can_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment_des',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='condition_apply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='correct_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='incorrect_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='past_issue_error',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reason_mistake',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='updated_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
