# Generated by Django 5.1.1 on 2024-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_process', '0002_alter_issue_can_name_alter_issue_comment_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_infor',
            name='base_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='event_coordinator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='gdr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='mnemoic_link',
            field=models.TextField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='spec_cate_link',
            field=models.TextField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='spec_link',
            field=models.TextField(max_length=2100, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='storage_period',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_infor',
            name='trim_mrd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
